# ================== PROFILE: prod ==================
#---
spring.config.activate.on-profile=prod
spring.config.import=optional:file:.env.prod[.properties]

# Khong log lai SQL ra log du co bat DEBUG (nang & leak data)
spring.jpa.show-sql=false

# Tat devtools neu lo con sot tren classpath luc build prod (devtools thuong tu tat khi chay tu jar dong goi nhung bo vao cho chac)
spring.devtools.restart.enabled=false

management.endpoint.health.show-details=never
